/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: 'en' | 'fr'
  navHome?: string
  navAbout?: string
  navPrograms?: string
  navServices?: string
  navVentures?: string
  navCommunity?: string
  navWorkWithUs?: string
  navContact?: string
  signIn?: string
  signUp?: string
  footerTagline?: string
  footerQuickLinks?: string
  footerLegal?: string
  footerPrivacy?: string
  footerTerms?: string
  footerConnect?: string
  footerRights?: string
  readMore?: string
  learnMore?: string
  contactUs?: string
  applyNow?: string
  viewCaseStudy?: string
  readCaseStudy?: string
  comingSoon?: string
  registerNow?: string
  watchRecording?: string
  heroTitle?: string
  heroSubtitle?: string
  heroCtaPrimary?: string
  heroCtaSecondary?: string
  whatWeDoTitle?: string
  whatWeDoSubtitle?: string
  programsTitle?: string
  programsDescription?: string
  programsCta?: string
  servicesTitle?: string
  servicesDescription?: string
  servicesCta?: string
  communityTitle?: string
  communityDescription?: string
  communityCta?: string
  successStoriesTitle?: string
  successStoriesSubtitle?: string
  venturesComingSoon?: string
  viewAllVentures?: string
  howCanWeHelpTitle?: string
  howCanWeHelpSubtitle?: string
  forEntrepreneursTitle?: string
  forEntrepreneursDescription?: string
  forEntrepreneursCta?: string
  forPartnersTitle?: string
  forPartnersDescription?: string
  forPartnersCta?: string
  forMentorsTitle?: string
  forMentorsDescription?: string
  forMentorsCta?: string
  aboutPageTitle?: string
  aboutPageDescription?: string
  aboutOurStoryTitle?: string
  aboutOurStoryParagraph1?: string
  aboutOurStoryParagraph2?: string
  aboutOurStoryParagraph3?: string
  aboutV2SApproachTitle?: string
  aboutV2SApproachDescription?: string
  aboutVisionTitle?: string
  aboutVisionDescription?: string
  aboutStructureTitle?: string
  aboutStructureDescription?: string
  aboutEightToolsTitle?: string
  aboutTool1?: string
  aboutTool2?: string
  aboutTool3?: string
  aboutTool4?: string
  aboutTool5?: string
  aboutTool6?: string
  aboutTool7?: string
  aboutTool8?: string
  aboutMissionTitle?: string
  aboutMissionStatement?: string
  aboutVisionStatementTitle?: string
  aboutVisionStatement?: string
  aboutTeamTitle?: string
  aboutTeamDescription?: string
  aboutTeamComingSoon?: string
  aboutPartnersTitle?: string
  aboutPartnersDescription?: string
  aboutStrategicPartnersTitle?: string
  aboutStrategicPartnersDescription?: string
  aboutExpertAdvisorsTitle?: string
  aboutExpertAdvisorsDescription?: string
  aboutEcosystemPartnersTitle?: string
  aboutEcosystemPartnersDescription?: string
  aboutPartnershipInterest?: string
  aboutLearnPartnershipOpportunities?: string
  aboutValuesTitle?: string
  aboutExcellenceTitle?: string
  aboutExcellenceDescription?: string
  aboutInnovationTitle?: string
  aboutInnovationDescription?: string
  aboutPartnershipTitle?: string
  aboutPartnershipDescription?: string
  ourStory?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  v2sApproach?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  mission?: string
  vision?: string
  programsPageTitle?: string
  programsPageDescription?: string
  programsFlagshipBadge?: string
  programsEightToolsTitle?: string
  programsWhoCanApplyTitle?: string
  programsWhoCanApplySubtitle?: string
  programsExpectedOutcomesTitle?: string
  programsExpectedOutcomesSubtitle?: string
  programsHekimaTimeTitle?: string
  programsHekimaTimeDescription?: string
  programsUpcomingSessionsTitle?: string
  programsPastSessionsTitle?: string
  programsViewAllHekimaTime?: string
  communityPageTitle?: string
  communityPageDescription?: string
  communityHekimaTimeTitle?: string
  communityHekimaTimeSubtitle?: string
  communityHekimaTimeDescription?: string
  communityUpcomingSessionsTitle?: string
  communityPastSessionsTitle?: string
  communitySessionsComingSoon?: string
  communityLatestInsightsTitle?: string
  communityLatestInsightsDescription?: string
  communityReadMore?: string
  communityViewAllPosts?: string
  communityJoinNetworkTitle?: string
  communityJoinNetworkDescription?: string
  communityEntrepreneursTitle?: string
  communityEntrepreneursDescription?: string
  communityLearnMoreCta?: string
  communityPartnersTitle?: string
  communityPartnersDescription?: string
  communityPartnerWithUsCta?: string
  communityMentorsTitle?: string
  communityMentorsDescription?: string
  communityJoinNetworkCta?: string
  communityStayUpdatedTitle?: string
  communityEmailPlaceholder?: string
  communitySubscribeCta?: string
  communityNotificationMessage?: string
  communityQuestionsTitle?: string
  communityQuestionsDescription?: string
  communityChatWhatsAppCta?: string
  servicesPageTitle?: string
  servicesPageDescription?: string
  servicesScheduleConsultation?: string
  servicesHowItWorksTitle?: string
  servicesConsultationTitle?: string
  servicesConsultationDescription?: string
  servicesCustomPlanTitle?: string
  servicesCustomPlanDescription?: string
  servicesImplementationTitle?: string
  servicesImplementationDescription?: string
  workWithUsPageTitle?: string
  workWithUsPageDescription?: string
  workWithUsEntrepreneursTitle?: string
  workWithUsEntrepreneursSubtitle?: string
  workWithUsEntrepreneursDescription?: string
  workWithUsEntrepreneursLearnMore?: string
  workWithUsPartnersTitle?: string
  workWithUsPartnersSubtitle?: string
  workWithUsPartnersDescription?: string
  workWithUsPartnersLearnMore?: string
  workWithUsMentorsTitle?: string
  workWithUsMentorsSubtitle?: string
  workWithUsMentorsDescription?: string
  workWithUsMentorsLearnMore?: string
  venturesPageTitle?: string
  venturesPageDescription?: string
  venturesNoVentures?: string
  venturesFeaturedBadge?: string
  venturesReadCaseStudy?: string
  componentBusinessAssessmentTitle?: string
  componentBusinessAssessmentDescription?: string
  componentScheduleFreeAssessment?: string
  componentGetFreeEvaluation?: string
  componentApplyNow?: string
  componentEventUpcoming?: string
  componentEventRecorded?: string
  componentEventSpeakers?: string
  componentContactFormTitle?: string
  componentContactFormDescription?: string
  componentContactFirstName?: string
  componentContactLastName?: string
  componentContactCompany?: string
  componentContactSubject?: string
  componentContactSending?: string
  componentContactSuccessMessage?: string
  componentImpactBusinessesSupported?: string
  componentImpactHekimaSessions?: string
  componentImpactRegionsServed?: string
  componentImpactJobsCreated?: string
  contactPageTitle?: string
  contactPageDescription?: string
  contactResponseTime?: string
  contactEmailAddress?: string
  contactOurOffices?: string
  contactGomaOffice?: string
  contactKinshasaOffice?: string
  contactAddressComingSoon?: string
  contactFollowUs?: string
  contactNeedHelp?: string
  contactNeedHelpDescription?: string
  whatsapp?: string
  email?: string
  emailPartnerships?: string
  addressGoma?: string
  addressKinshasa?: string
  linkedin?: string
  twitter?: string
  instagram?: string
  facebook?: string
}

export type ImpactMetrics = {
  _id: string
  _type: 'impactMetrics'
  _createdAt: string
  _updatedAt: string
  _rev: string
  year?: number
  businessesSupported?: number
  hekimaSessions?: number
  sessionsAttendees?: number
  regionsServed?: number
  jobsCreated?: number
  revenueGrowth?: string
  totalInvestment?: string
  programGraduates?: number
  customMetrics?: Array<{
    labelEn?: string
    labelFr?: string
    value?: string
    _key: string
  }>
  isCurrent?: boolean
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  titleEn?: string
  titleFr?: string
  slug?: Slug
  series?: 'hekima-time' | 'workshop' | 'networking' | 'other'
  descriptionEn?: string
  descriptionFr?: string
  eventDate?: string
  duration?: number
  format?: 'virtual' | 'in-person' | 'hybrid'
  location?: string
  speakers?: Array<{
    name?: string
    title?: string
    photo?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _key: string
  }>
  topicsEn?: Array<string>
  topicsFr?: Array<string>
  registrationUrl?: string
  maxAttendees?: number
  recordingUrl?: string
  keyTakeawaysEn?: Array<string>
  keyTakeawaysFr?: Array<string>
  status?: 'upcoming' | 'in-progress' | 'completed' | 'cancelled'
  featured?: boolean
}

export type Program = {
  _id: string
  _type: 'program'
  _createdAt: string
  _updatedAt: string
  _rev: string
  nameEn?: string
  nameFr?: string
  slug?: Slug
  shortDescriptionEn?: string
  shortDescriptionFr?: string
  fullDescriptionEn?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  fullDescriptionFr?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  programType?: 'v2s' | 'workshop' | 'direct-support' | 'mentorship'
  duration?: string
  format?: string
  eligibilityEn?: Array<string>
  eligibilityFr?: Array<string>
  keyFeatures?: Array<{
    titleEn?: string
    titleFr?: string
    descriptionEn?: string
    descriptionFr?: string
    _key: string
  }>
  outcomesEn?: Array<string>
  outcomesFr?: Array<string>
  curriculum?: Array<{
    week?: number
    toolNameEn?: string
    toolNameFr?: string
    descriptionEn?: string
    descriptionFr?: string
    _key: string
  }>
  testimonials?: Array<{
    quoteEn?: string
    quoteFr?: string
    author?: string
    company?: string
    _key: string
  }>
  applicationUrl?: string
  isActive?: boolean
  order?: number
}

export type Venture = {
  _id: string
  _type: 'venture'
  _createdAt: string
  _updatedAt: string
  _rev: string
  nameEn?: string
  nameFr?: string
  slug?: Slug
  taglineEn?: string
  taglineFr?: string
  logo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  sector?:
    | 'agro-food'
    | 'food-beverage'
    | 'legal-tech'
    | 'media'
    | 'agriculture'
    | 'technology'
    | 'education'
    | 'healthcare'
    | 'other'
  location?: string
  descriptionEn?: string
  descriptionFr?: string
  metricsHighlightEn?: string
  metricsHighlightFr?: string
  websiteUrl?: string
  caseStudy?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'caseStudy'
  }
  featured?: boolean
  order?: number
}

export type CaseStudy = {
  _id: string
  _type: 'caseStudy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  titleEn?: string
  titleFr?: string
  slug?: Slug
  venture?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'venture'
  }
  sector?: string
  location?: string
  program?: string
  heroImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
  challengeEn?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  challengeFr?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  partnershipEn?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  partnershipFr?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  impactEn?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  impactFr?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  quote?: {
    textEn?: string
    textFr?: string
    author?: string
    authorTitle?: string
  }
  whyItMattersEn?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  whyItMattersFr?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  impactImages?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }>
  publishedAt?: string
  featured?: boolean
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  titleEn?: string
  titleFr?: string
  slug?: Slug
  excerptEn?: string
  excerptFr?: string
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'teamMember'
  }
  publishedAt?: string
  categories?: Array<string>
  tags?: Array<string>
  contentEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  contentFr?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  featured?: boolean
  seo?: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type TeamMember = {
  _id: string
  _type: 'teamMember'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  roleEn?: string
  roleFr?: string
  bioEn?: string
  bioFr?: string
  photo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  expertiseEn?: Array<string>
  expertiseFr?: Array<string>
  linkedIn?: string
  twitter?: string
  email?: string
  order?: number
  featured?: boolean
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | SiteSettings
  | ImpactMetrics
  | Event
  | Program
  | Venture
  | CaseStudy
  | Post
  | TeamMember
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
