import { defineField, defineType } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'navigation', title: 'Navigation' },
    { name: 'footer', title: 'Footer' },
    { name: 'common', title: 'Common UI' },
    { name: 'homepage', title: 'Homepage' },
    { name: 'about', title: 'About Page' },
    { name: 'programs', title: 'Programs Page' },
    { name: 'community', title: 'Community Page' },
    { name: 'services', title: 'Services Page' },
    { name: 'workWithUs', title: 'Work With Us Page' },
    { name: 'ventures', title: 'Ventures Page' },
    { name: 'components', title: 'Shared Components' },
    { name: 'contact', title: 'Contact Info' },
  ],
  fields: [
    // Language selector
    defineField({
      name: 'language',
      title: 'Language',
      type: 'string',
      options: {
        list: [
          { title: 'English', value: 'en' },
          { title: 'French', value: 'fr' },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),

    // Navigation
    defineField({
      name: 'navHome',
      title: 'Navigation: Home',
      type: 'string',
      initialValue: 'Home',
      group: 'navigation',
    }),
    defineField({
      name: 'navAbout',
      title: 'Navigation: About',
      type: 'string',
      initialValue: 'About',
      group: 'navigation',
    }),
    defineField({
      name: 'navPrograms',
      title: 'Navigation: Programs',
      type: 'string',
      initialValue: 'Programs',
      group: 'navigation',
    }),
    defineField({
      name: 'navServices',
      title: 'Navigation: Services',
      type: 'string',
      initialValue: 'Services',
      group: 'navigation',
    }),
    defineField({
      name: 'navVentures',
      title: 'Navigation: Ventures',
      type: 'string',
      initialValue: 'Ventures',
      group: 'navigation',
    }),
    defineField({
      name: 'navCommunity',
      title: 'Navigation: Community',
      type: 'string',
      initialValue: 'Community',
      group: 'navigation',
    }),
    defineField({
      name: 'navWorkWithUs',
      title: 'Navigation: Work With Us',
      type: 'string',
      initialValue: 'Work With Us',
      group: 'navigation',
    }),
    defineField({
      name: 'navContact',
      title: 'Navigation: Contact',
      type: 'string',
      initialValue: 'Contact',
      group: 'navigation',
    }),
    defineField({
      name: 'signIn',
      title: 'Sign In',
      type: 'string',
      initialValue: 'Sign In',
      group: 'navigation',
    }),
    defineField({
      name: 'signUp',
      title: 'Sign Up',
      type: 'string',
      initialValue: 'Sign Up',
      group: 'navigation',
    }),

    // Footer
    defineField({
      name: 'footerTagline',
      title: 'Footer Tagline',
      type: 'string',
      initialValue: 'Building scalable businesses in the DRC',
      group: 'footer',
    }),
    defineField({
      name: 'footerQuickLinks',
      title: 'Quick Links Heading',
      type: 'string',
      initialValue: 'Quick Links',
      group: 'footer',
    }),
    defineField({
      name: 'footerLegal',
      title: 'Legal Heading',
      type: 'string',
      initialValue: 'Legal',
      group: 'footer',
    }),
    defineField({
      name: 'footerPrivacy',
      title: 'Privacy Policy',
      type: 'string',
      initialValue: 'Privacy Policy',
      group: 'footer',
    }),
    defineField({
      name: 'footerTerms',
      title: 'Terms of Service',
      type: 'string',
      initialValue: 'Terms of Service',
      group: 'footer',
    }),
    defineField({
      name: 'footerConnect',
      title: 'Connect With Us',
      type: 'string',
      initialValue: 'Connect With Us',
      group: 'footer',
    }),
    defineField({
      name: 'footerRights',
      title: 'Rights Reserved',
      type: 'string',
      initialValue: 'All rights reserved.',
      group: 'footer',
    }),

    // Common UI
    defineField({
      name: 'readMore',
      title: 'Read More',
      type: 'string',
      initialValue: 'Read more',
      group: 'common',
    }),
    defineField({
      name: 'learnMore',
      title: 'Learn More',
      type: 'string',
      initialValue: 'Learn More',
      group: 'common',
    }),
    defineField({
      name: 'contactUs',
      title: 'Contact Us',
      type: 'string',
      initialValue: 'Contact Us',
      group: 'common',
    }),
    defineField({
      name: 'applyNow',
      title: 'Apply Now',
      type: 'string',
      initialValue: 'Apply Now',
      group: 'common',
    }),
    defineField({
      name: 'viewCaseStudy',
      title: 'View Case Study',
      type: 'string',
      initialValue: 'View Case Study',
      group: 'common',
    }),
    defineField({
      name: 'readCaseStudy',
      title: 'Read Case Study',
      type: 'string',
      initialValue: 'Read Case Study',
      group: 'common',
    }),
    defineField({
      name: 'comingSoon',
      title: 'Coming Soon',
      type: 'string',
      initialValue: 'Coming soon',
      group: 'common',
    }),
    defineField({
      name: 'registerNow',
      title: 'Register Now',
      type: 'string',
      initialValue: 'Register Now',
      group: 'common',
    }),
    defineField({
      name: 'watchRecording',
      title: 'Watch Recording',
      type: 'string',
      initialValue: 'Watch Recording',
      group: 'common',
    }),

    // Homepage Content - Marketing copy only
    defineField({
      name: 'heroTitle',
      title: 'Hero Title',
      type: 'text',
      group: 'homepage',
      description: 'Main headline on homepage (marketing copy)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero Subtitle',
      type: 'text',
      group: 'homepage',
      description: 'Supporting text below hero title (marketing copy)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroCtaPrimary',
      title: 'Hero CTA Primary Button',
      type: 'string',
      group: 'homepage',
      description: 'Text for primary call-to-action button',
    }),
    defineField({
      name: 'heroCtaSecondary',
      title: 'Hero CTA Secondary Button',
      type: 'string',
      group: 'homepage',
      description: 'Text for secondary call-to-action button',
    }),
    defineField({
      name: 'whatWeDoTitle',
      title: 'What We Do - Title',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'whatWeDoSubtitle',
      title: 'What We Do - Subtitle',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'programsTitle',
      title: 'Programs Section - Title',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'programsDescription',
      title: 'Programs Section - Description',
      type: 'text',
      group: 'homepage',
    }),
    defineField({
      name: 'programsCta',
      title: 'Programs Section - CTA Text',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'servicesTitle',
      title: 'Services Section - Title',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'servicesDescription',
      title: 'Services Section - Description',
      type: 'text',
      group: 'homepage',
    }),
    defineField({
      name: 'servicesCta',
      title: 'Services Section - CTA Text',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'communityTitle',
      title: 'Community Section - Title',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'communityDescription',
      title: 'Community Section - Description',
      type: 'text',
      group: 'homepage',
    }),
    defineField({
      name: 'communityCta',
      title: 'Community Section - CTA Text',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'successStoriesTitle',
      title: 'Success Stories - Title',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'successStoriesSubtitle',
      title: 'Success Stories - Subtitle',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'venturesComingSoon',
      title: 'Ventures Coming Soon Text',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'viewAllVentures',
      title: 'View All Ventures Button',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'howCanWeHelpTitle',
      title: 'How Can We Help - Title',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'howCanWeHelpSubtitle',
      title: 'How Can We Help - Subtitle',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'forEntrepreneursTitle',
      title: 'For Entrepreneurs - Title',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'forEntrepreneursDescription',
      title: 'For Entrepreneurs - Description',
      type: 'text',
      group: 'homepage',
    }),
    defineField({
      name: 'forEntrepreneursCta',
      title: 'For Entrepreneurs - CTA Button',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'forPartnersTitle',
      title: 'For Partners & Investors - Title',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'forPartnersDescription',
      title: 'For Partners & Investors - Description',
      type: 'text',
      group: 'homepage',
    }),
    defineField({
      name: 'forPartnersCta',
      title: 'For Partners & Investors - CTA Button',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'forMentorsTitle',
      title: 'For Mentors & Experts - Title',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'forMentorsDescription',
      title: 'For Mentors & Experts - Description',
      type: 'text',
      group: 'homepage',
    }),
    defineField({
      name: 'forMentorsCta',
      title: 'For Mentors & Experts - CTA Button',
      type: 'string',
      group: 'homepage',
    }),

    // About Page Content
    defineField({
      name: 'aboutPageTitle',
      title: 'About - Page Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutPageDescription',
      title: 'About - Page Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutOurStoryTitle',
      title: 'About - Our Story Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutOurStoryParagraph1',
      title: 'About - Our Story Paragraph 1',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutOurStoryParagraph2',
      title: 'About - Our Story Paragraph 2',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutOurStoryParagraph3',
      title: 'About - Our Story Paragraph 3',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutV2SApproachTitle',
      title: 'About - V2S Approach Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutV2SApproachDescription',
      title: 'About - V2S Approach Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutVisionTitle',
      title: 'About - Vision Section Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutVisionDescription',
      title: 'About - Vision Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutStructureTitle',
      title: 'About - Structure Section Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutStructureDescription',
      title: 'About - Structure Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutEightToolsTitle',
      title: 'About - Eight Tools Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutTool1',
      title: 'Tool 1 - Vision & Mission',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutTool2',
      title: 'Tool 2 - Customer Segmentation',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutTool3',
      title: 'Tool 3 - Financial Modeling',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutTool4',
      title: 'Tool 4 - Sales Process',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutTool5',
      title: 'Tool 5 - Team Structure',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutTool6',
      title: 'Tool 6 - Operational Workflows',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutTool7',
      title: 'Tool 7 - Market Access',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutTool8',
      title: 'Tool 8 - Growth Metrics',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutMissionTitle',
      title: 'About - Mission Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutMissionStatement',
      title: 'About - Mission Statement',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutVisionStatementTitle',
      title: 'About - Vision Statement Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutVisionStatement',
      title: 'About - Vision Statement',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutTeamTitle',
      title: 'About - Team Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutTeamDescription',
      title: 'About - Team Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutTeamComingSoon',
      title: 'About - Team Coming Soon',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutPartnersTitle',
      title: 'About - Partners Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutPartnersDescription',
      title: 'About - Partners Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutStrategicPartnersTitle',
      title: 'About - Strategic Partners Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutStrategicPartnersDescription',
      title: 'About - Strategic Partners Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutExpertAdvisorsTitle',
      title: 'About - Expert Advisors Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutExpertAdvisorsDescription',
      title: 'About - Expert Advisors Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutEcosystemPartnersTitle',
      title: 'About - Ecosystem Partners Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutEcosystemPartnersDescription',
      title: 'About - Ecosystem Partners Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutPartnershipInterest',
      title: 'About - Partnership Interest Question',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutLearnPartnershipOpportunities',
      title: 'About - Learn Partnership Opportunities CTA',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutValuesTitle',
      title: 'About - Values Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutExcellenceTitle',
      title: 'About - Excellence Value Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutExcellenceDescription',
      title: 'About - Excellence Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutInnovationTitle',
      title: 'About - Innovation Value Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutInnovationDescription',
      title: 'About - Innovation Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'aboutPartnershipTitle',
      title: 'About - Partnership Value Title',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutPartnershipDescription',
      title: 'About - Partnership Description',
      type: 'text',
      group: 'about',
    }),
    defineField({
      name: 'ourStory',
      title: 'Our Story',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'about',
      description: 'The story behind Kilalo and why we exist',
    }),
    defineField({
      name: 'v2sApproach',
      title: 'V2S Approach Explanation',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'about',
      description: 'Detailed explanation of the Vision & Structure methodology',
    }),
    defineField({
      name: 'mission',
      title: 'Mission Statement',
      type: 'text',
      group: 'about',
      description: 'Official mission statement',
    }),
    defineField({
      name: 'vision',
      title: 'Vision Statement',
      type: 'text',
      group: 'about',
      description: 'Official vision statement',
    }),

    // Programs Page
    defineField({
      name: 'programsPageTitle',
      title: 'Programs - Page Title',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsPageDescription',
      title: 'Programs - Page Description',
      type: 'text',
      group: 'programs',
    }),
    defineField({
      name: 'programsFlagshipBadge',
      title: 'Programs - Flagship Badge Text',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsEightToolsTitle',
      title: 'Programs - Eight Tools Title',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsWhoCanApplyTitle',
      title: 'Programs - Who Can Apply Title',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsWhoCanApplySubtitle',
      title: 'Programs - Who Can Apply Subtitle',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsExpectedOutcomesTitle',
      title: 'Programs - Expected Outcomes Title',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsExpectedOutcomesSubtitle',
      title: 'Programs - Expected Outcomes Subtitle',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsHekimaTimeTitle',
      title: 'Programs - Hekima Time Title',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsHekimaTimeDescription',
      title: 'Programs - Hekima Time Description',
      type: 'text',
      group: 'programs',
    }),
    defineField({
      name: 'programsUpcomingSessionsTitle',
      title: 'Programs - Upcoming Sessions Title',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsPastSessionsTitle',
      title: 'Programs - Past Sessions Title',
      type: 'string',
      group: 'programs',
    }),
    defineField({
      name: 'programsViewAllHekimaTime',
      title: 'Programs - View All Hekima Time CTA',
      type: 'string',
      group: 'programs',
    }),

    // Community Page
    defineField({
      name: 'communityPageTitle',
      title: 'Community - Page Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityPageDescription',
      title: 'Community - Page Description',
      type: 'text',
      group: 'community',
    }),
    defineField({
      name: 'communityHekimaTimeTitle',
      title: 'Community - Hekima Time Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityHekimaTimeSubtitle',
      title: 'Community - Hekima Time Subtitle',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityHekimaTimeDescription',
      title: 'Community - Hekima Time Description',
      type: 'text',
      group: 'community',
    }),
    defineField({
      name: 'communityUpcomingSessionsTitle',
      title: 'Community - Upcoming Sessions Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityPastSessionsTitle',
      title: 'Community - Past Sessions Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communitySessionsComingSoon',
      title: 'Community - Sessions Coming Soon',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityLatestInsightsTitle',
      title: 'Community - Latest Insights Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityLatestInsightsDescription',
      title: 'Community - Latest Insights Description',
      type: 'text',
      group: 'community',
    }),
    defineField({
      name: 'communityReadMore',
      title: 'Community - Read More CTA',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityViewAllPosts',
      title: 'Community - View All Posts CTA',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityJoinNetworkTitle',
      title: 'Community - Join Network Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityJoinNetworkDescription',
      title: 'Community - Join Network Description',
      type: 'text',
      group: 'community',
    }),
    defineField({
      name: 'communityEntrepreneursTitle',
      title: 'Community - Entrepreneurs Card Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityEntrepreneursDescription',
      title: 'Community - Entrepreneurs Description',
      type: 'text',
      group: 'community',
    }),
    defineField({
      name: 'communityLearnMoreCta',
      title: 'Community - Learn More CTA',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityPartnersTitle',
      title: 'Community - Partners Card Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityPartnersDescription',
      title: 'Community - Partners Description',
      type: 'text',
      group: 'community',
    }),
    defineField({
      name: 'communityPartnerWithUsCta',
      title: 'Community - Partner With Us CTA',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityMentorsTitle',
      title: 'Community - Mentors Card Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityMentorsDescription',
      title: 'Community - Mentors Description',
      type: 'text',
      group: 'community',
    }),
    defineField({
      name: 'communityJoinNetworkCta',
      title: 'Community - Join Network CTA',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityStayUpdatedTitle',
      title: 'Community - Stay Updated Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityEmailPlaceholder',
      title: 'Community - Email Placeholder',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communitySubscribeCta',
      title: 'Community - Subscribe CTA',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityNotificationMessage',
      title: 'Community - Notification Message',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityQuestionsTitle',
      title: 'Community - Questions Title',
      type: 'string',
      group: 'community',
    }),
    defineField({
      name: 'communityQuestionsDescription',
      title: 'Community - Questions Description',
      type: 'text',
      group: 'community',
    }),
    defineField({
      name: 'communityChatWhatsAppCta',
      title: 'Community - Chat on WhatsApp CTA',
      type: 'string',
      group: 'community',
    }),

    // Services Page
    defineField({
      name: 'servicesPageTitle',
      title: 'Services - Page Title',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesPageDescription',
      title: 'Services - Page Description',
      type: 'text',
      group: 'services',
    }),
    defineField({
      name: 'servicesScheduleConsultation',
      title: 'Services - Schedule Consultation CTA',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesHowItWorksTitle',
      title: 'Services - How It Works Title',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesConsultationTitle',
      title: 'Services - Consultation Step Title',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesConsultationDescription',
      title: 'Services - Consultation Description',
      type: 'text',
      group: 'services',
    }),
    defineField({
      name: 'servicesCustomPlanTitle',
      title: 'Services - Custom Plan Title',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesCustomPlanDescription',
      title: 'Services - Custom Plan Description',
      type: 'text',
      group: 'services',
    }),
    defineField({
      name: 'servicesImplementationTitle',
      title: 'Services - Implementation Title',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesImplementationDescription',
      title: 'Services - Implementation Description',
      type: 'text',
      group: 'services',
    }),

    // Work With Us Page
    defineField({
      name: 'workWithUsPageTitle',
      title: 'Work With Us - Page Title',
      type: 'string',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsPageDescription',
      title: 'Work With Us - Page Description',
      type: 'text',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsEntrepreneursTitle',
      title: 'Work With Us - Entrepreneurs Title',
      type: 'string',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsEntrepreneursSubtitle',
      title: 'Work With Us - Entrepreneurs Subtitle',
      type: 'string',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsEntrepreneursDescription',
      title: 'Work With Us - Entrepreneurs Description',
      type: 'text',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsEntrepreneursLearnMore',
      title: 'Work With Us - Entrepreneurs Learn More CTA',
      type: 'string',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsPartnersTitle',
      title: 'Work With Us - Partners Title',
      type: 'string',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsPartnersSubtitle',
      title: 'Work With Us - Partners Subtitle',
      type: 'string',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsPartnersDescription',
      title: 'Work With Us - Partners Description',
      type: 'text',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsPartnersLearnMore',
      title: 'Work With Us - Partners Learn More CTA',
      type: 'string',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsMentorsTitle',
      title: 'Work With Us - Mentors Title',
      type: 'string',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsMentorsSubtitle',
      title: 'Work With Us - Mentors Subtitle',
      type: 'string',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsMentorsDescription',
      title: 'Work With Us - Mentors Description',
      type: 'text',
      group: 'workWithUs',
    }),
    defineField({
      name: 'workWithUsMentorsLearnMore',
      title: 'Work With Us - Mentors Learn More CTA',
      type: 'string',
      group: 'workWithUs',
    }),

    // Ventures Page
    defineField({
      name: 'venturesPageTitle',
      title: 'Ventures - Page Title',
      type: 'string',
      group: 'ventures',
    }),
    defineField({
      name: 'venturesPageDescription',
      title: 'Ventures - Page Description',
      type: 'text',
      group: 'ventures',
    }),
    defineField({
      name: 'venturesComingSoon',
      title: 'Ventures - Coming Soon Message',
      type: 'string',
      group: 'ventures',
    }),
    defineField({
      name: 'venturesFeaturedBadge',
      title: 'Ventures - Featured Badge',
      type: 'string',
      group: 'ventures',
    }),
    defineField({
      name: 'venturesReadCaseStudy',
      title: 'Ventures - Read Case Study CTA',
      type: 'string',
      group: 'ventures',
    }),

    // Shared Components
    defineField({
      name: 'componentBusinessAssessmentTitle',
      title: 'Component - Business Assessment Title',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentBusinessAssessmentDescription',
      title: 'Component - Business Assessment Description',
      type: 'text',
      group: 'components',
    }),
    defineField({
      name: 'componentScheduleFreeAssessment',
      title: 'Component - Schedule Free Assessment CTA',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentGetFreeEvaluation',
      title: 'Component - Get Free Evaluation Title',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentApplyNow',
      title: 'Component - Apply Now CTA',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentEventUpcoming',
      title: 'Component - Event Upcoming Badge',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentEventRecorded',
      title: 'Component - Event Recorded Badge',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentEventSpeakers',
      title: 'Component - Event Speakers Label',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentContactFormTitle',
      title: 'Component - Contact Form Title',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentContactFormDescription',
      title: 'Component - Contact Form Description',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentContactFirstName',
      title: 'Component - First Name Label',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentContactLastName',
      title: 'Component - Last Name Label',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentContactCompany',
      title: 'Component - Company Label',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentContactSubject',
      title: 'Component - Subject Label',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentContactSending',
      title: 'Component - Sending Button Text',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentContactSuccessMessage',
      title: 'Component - Success Message',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentImpactBusinessesSupported',
      title: 'Component - Businesses Supported Label',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentImpactHekimaSessions',
      title: 'Component - Hekima Sessions Label',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentImpactRegionsServed',
      title: 'Component - Regions Served Label',
      type: 'string',
      group: 'components',
    }),
    defineField({
      name: 'componentImpactJobsCreated',
      title: 'Component - Jobs Created Label',
      type: 'string',
      group: 'components',
    }),

    // Contact Page Additional Fields
    defineField({
      name: 'contactPageTitle',
      title: 'Contact - Page Title',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactPageDescription',
      title: 'Contact - Page Description',
      type: 'text',
      group: 'contact',
    }),
    defineField({
      name: 'contactResponseTime',
      title: 'Contact - Response Time Message',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactEmailAddress',
      title: 'Contact - Email Address Display',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactOurOffices',
      title: 'Contact - Our Offices Title',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactGomaOffice',
      title: 'Contact - Goma Office Label',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactKinshasa Office',
      title: 'Contact - Kinshasa Office Label',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactAddressComingSoon',
      title: 'Contact - Address Coming Soon',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactFollowUs',
      title: 'Contact - Follow Us Title',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactNeedHelp',
      title: 'Contact - Need Help Title',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactNeedHelpDescription',
      title: 'Contact - Need Help Description',
      type: 'text',
      group: 'contact',
    }),

    // Contact Information
    defineField({
      name: 'whatsapp',
      title: 'WhatsApp Number',
      type: 'string',
      group: 'contact',
      description: 'Include country code (e.g., +243...)',
    }),
    defineField({
      name: 'email',
      title: 'General Email',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.email(),
    }),
    defineField({
      name: 'emailPartnerships',
      title: 'Partnerships Email',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.email(),
    }),
    defineField({
      name: 'addressGoma',
      title: 'Goma Office Address',
      type: 'text',
      group: 'contact',
    }),
    defineField({
      name: 'addressKinshasa',
      title: 'Kinshasa Office Address',
      type: 'text',
      group: 'contact',
    }),
    defineField({
      name: 'linkedin',
      title: 'LinkedIn URL',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'twitter',
      title: 'Twitter/X URL',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'instagram',
      title: 'Instagram URL',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'facebook',
      title: 'Facebook URL',
      type: 'url',
      group: 'contact',
    }),
  ],
  preview: {
    select: {
      title: 'language',
    },
    prepare({ title }) {
      return {
        title: `Site Settings (${title === 'en' ? 'English' : 'Français'})`,
      }
    },
  },
})
